[package]
name = "AsgardManager"
version = "0.1.0"
edition = "2024"

[dependencies]
applevisor = "0.1.3"  # Rust bindings for Apple Silicon Hypervisor Framework
tokio = { version = "1.45.0", features = ["full"] }

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-sectcreate,__TEXT,__info_plist,test.entitlements"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-args=-Wl,-sectcreate,__TEXT,__info_plist,test.entitlements"]